### ISSUE TITLE
Random gender

### ISSUE THREAD

**Issue by Kignuf** [nodeca/charlatan#15]
Hello,
Thanks for this tool.
I'm using it for a small project, however I could not find a way to generate a random gender between male and female.

Is it something planned ?

**Comment by puzrin** [comment]
That's a port of https://github.com/stympy/faker, we do not change it anyhow. I'd recomment to see there if such function is available at all.

But, in your case, seems you need just a simple random:

```js
console.log([ 'male', 'female' ][Math.round(Math.random())])
```
